/**
 * Pre-build: generates static slugs for static export.
 * Note: only slugs WITHOUT the trailing "index" segment are emitted —
 * Fumadocs maps index.mdx to its parent path, so ["section","index"]
 * would resolve to a notFound() error page in static export.
 */
import { writeFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const contentDir = join(__dirname, '..', 'content', 'docs');
const slugs = [];

function walkDir(dir, parentSlugs = []) {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === 'meta.json') continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      walkDir(fullPath, [...parentSlugs, entry.name]);
    } else if (entry.name.endsWith('.mdx')) {
      const name = entry.name.replace(/\.mdx$/, '');
      if (name === 'index') {
        // index.mdx maps to its parent path only — never emit "index" itself
        slugs.push([...parentSlugs]);
      } else {
        slugs.push([...parentSlugs, name]);
      }
    }
  }
}

walkDir(contentDir);

// Root page: content/docs/index.mdx maps to [] (already pushed by walkDir).
// Only keep a fallback when the root index.mdx exists to avoid a 404 page
// sneaking into the export for a non-existent document.
if (!existsSync(join(contentDir, 'index.mdx')) && !slugs.some((s) => s.length === 0)) {
  console.warn('Warning: content/docs/index.mdx is missing — /docs root will not be generated');
}

// Deduplicate
const seen = new Set();
const unique = slugs.filter(s => {
  const key = s.join('/');
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

console.log(`Found ${unique.length} slugs`);

// Write static params for Next.js generateStaticParams
const outPath = join(__dirname, '..', 'lib', 'static-slugs.ts');
writeFileSync(outPath, `// Auto-generated by scripts/generate-params.mjs\nexport const staticSlugs: string[][] = ${JSON.stringify(unique, null, 2)};\n`);
console.log(`Written to lib/static-slugs.ts`);
